MCU=atmega328p
F_CPU=14318180UL
PROGRAMMER?=usbtiny

TARGET=avr-nessynth-controller

SOURCES=main.c i2c-master.c uart.c ssd1306.c logo-paw-64x64.c glcdfont.c log.c sd.c fat32.c

LIBDIR=../lib/
include $(LIBDIR)/Makefile.inc
